# Generated by Django 3.2 on 2021-05-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Relaxing', 'Relaxing'), ('Sad', 'Sad')], max_length=30)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
